[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
pythonpath = . TMT-OS tmt-os-labs integrations agi_scripts agi_app agi_model
addopts = --tb=short -v
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
