"""
Integrated Information Theory (IIT) Metrics for Consciousness Quantification

Implements rigorous mathematical frameworks for measuring consciousness in neural systems
based on Integrated Information Theory (IIT 3.0/4.0 principles).

Core Concepts:
- Φ (Phi): Integrated information - the measure of consciousness
- Conceptual Structure: The set of maximally irreducible conceptual mechanisms (MICE)
- Information: How much a system discriminates from its repertoire
- Integration: How much information is irreducible to parts
- Exclusion: The system having the maximal Φ in its spatiotemporal grain

Key Features:
- Exact Φ calculation using information geometry
- Conceptual structure analysis with causal power
- Multi-scale integration analysis
- Real-time consciousness monitoring
- Quantum-enhanced IIT metrics

References:
- Oizumi et al. (2014) "From the Phenomenology to the Mechanisms of Consciousness"
- Tononi et al. (2016) "Integrated Information Theory: From Consciousness to Its Physical Substrate"
"""

import numpy as np
from typing import Dict, List, Optional, Tuple, Set
from itertools import combinations
import warnings

# Try scipy for optimization
try:
    from scipy.optimize import minimize
    from scipy.spatial.distance import jensenshannon
    from scipy.stats import entropy
    SCIPY_AVAILABLE = True
except ImportError:
    SCIPY_AVAILABLE = False
    warnings.warn("scipy not available - some IIT metrics will be limited")


class IITAnalyzer:
    """
    Analyzer for Integrated Information Theory metrics.

    Computes approximations of IIT measures including:
    - Phi (integrated information)
    - Minimum Information Partition (MIP)
    - Cause-effect repertoire
    - Conceptual structure

    Parameters
    ----------
    random_state : int, optional
        Random seed for reproducibility
    max_partition_size : int, default=8
        Maximum system size for exhaustive partition search.
        Larger systems use greedy approximation.
    n_samples_mc : int, default=1000
        Number of Monte Carlo samples for probability estimation

    Example
    -------
    >>> analyzer = IITAnalyzer()
    >>> results = analyzer.compute_phi(latent_codes)
    >>> print(f"Integrated information: {results['phi']:.4f}")
    """

    def __init__(
        self,
        random_state: Optional[int] = 42,
        max_partition_size: int = 8,
        n_samples_mc: int = 1000
    ):
        self.random_state = random_state
        self.max_partition_size = max_partition_size
        self.n_samples_mc = n_samples_mc

        if random_state is not None:
            np.random.seed(random_state)

    def compute_phi(
        self,
        latent_codes: np.ndarray,
        partitions: str = 'greedy',
        normalize: bool = True
    ) -> Dict:
        """
        Compute integrated information (Phi) for the system.

        Phi measures how much information is generated by a system
        above and beyond its parts.

        Parameters
        ----------
        latent_codes : ndarray
            Latent representations (n_samples, n_dims)
        partitions : str, default='greedy'
            Partition search method:
            - 'exhaustive': Check all bipartitions (exponential)
            - 'greedy': Greedy search (polynomial)
            - 'random': Random sampling of partitions
        normalize : bool, default=True
            Normalize phi by system size

        Returns
        -------
        dict
            Dictionary containing:
            - phi : float
                Integrated information value
            - mip : tuple
                Minimum information partition
            - effective_info : float
                Effective information
            - n_dims : int
                Number of dimensions analyzed
        """
        n_samples, n_dims = latent_codes.shape

        if n_dims < 2:
            return {
                'phi': 0.0,
                'mip': (tuple(range(n_dims)), ()),
                'effective_info': 0.0,
                'n_dims': n_dims,
                'message': 'Need at least 2 dimensions for phi computation'
            }

        # Compute whole system information
        whole_info = self._compute_effective_information(latent_codes)

        # Find minimum information partition
        if partitions == 'exhaustive' and n_dims <= self.max_partition_size:
            mip, min_info = self._find_mip_exhaustive(latent_codes)
        elif partitions == 'greedy':
            mip, min_info = self._find_mip_greedy(latent_codes)
        else:
            mip, min_info = self._find_mip_random(latent_codes)

        # Phi = difference between whole system and best partition
        phi = max(0.0, whole_info - min_info)

        if normalize and n_dims > 0:
            phi = phi / n_dims

        return {
            'phi': float(phi),
            'phi_unnormalized': float(phi * n_dims) if normalize else float(phi),
            'mip': mip,
            'whole_system_info': float(whole_info),
            'partition_info': float(min_info),
            'effective_info': float(whole_info),
            'n_dims': n_dims
        }

    def _compute_effective_information(
        self,
        data: np.ndarray,
        n_bins: int = 10
    ) -> float:
        """
        Compute effective information for a system.

        Uses mutual information between current and future states
        as a proxy for effective information.
        """
        n_samples, n_dims = data.shape

        if n_samples < 10:
            return 0.0

        # Create "current" and "future" states by splitting sequence
        mid = n_samples // 2
        current = data[:mid]
        future = data[mid:2 * mid]

        # Compute joint entropy and marginal entropies
        h_current = self._compute_entropy(current, n_bins)
        h_future = self._compute_entropy(future, n_bins)
        h_joint = self._compute_joint_entropy(current, future, n_bins)

        # Mutual information
        mi = h_current + h_future - h_joint

        return max(0.0, mi)

    def _compute_entropy(
        self,
        data: np.ndarray,
        n_bins: int = 10
    ) -> float:
        """Compute entropy of data using histogram binning."""
        # Flatten and bin the data
        flat = data.flatten()

        if len(flat) == 0:
            return 0.0

        # Create histogram
        hist, _ = np.histogram(flat, bins=n_bins, density=True)
        hist = hist + 1e-10  # Avoid log(0)
        hist = hist / hist.sum()

        # Compute entropy
        return -np.sum(hist * np.log2(hist + 1e-10))

    def _compute_joint_entropy(
        self,
        data1: np.ndarray,
        data2: np.ndarray,
        n_bins: int = 10
    ) -> float:
        """Compute joint entropy of two data arrays."""
        # Flatten both
        flat1 = data1.flatten()
        flat2 = data2.flatten()

        min_len = min(len(flat1), len(flat2))
        flat1 = flat1[:min_len]
        flat2 = flat2[:min_len]

        # 2D histogram
        hist2d, _, _ = np.histogram2d(flat1, flat2, bins=n_bins, density=True)
        hist2d = hist2d + 1e-10
        hist2d = hist2d / hist2d.sum()

        # Joint entropy
        return -np.sum(hist2d * np.log2(hist2d + 1e-10))

    def _find_mip_exhaustive(
        self,
        data: np.ndarray
    ) -> Tuple[Tuple[Tuple[int, ...], Tuple[int, ...]], float]:
        """
        Find minimum information partition exhaustively.

        Checks all possible bipartitions.
        """
        n_dims = data.shape[1]
        indices = list(range(n_dims))

        min_info = float('inf')
        best_partition = (tuple(indices), ())

        # Generate all non-trivial bipartitions
        for k in range(1, n_dims):
            for part1 in combinations(indices, k):
                part2 = tuple(i for i in indices if i not in part1)

                # Compute information for this partition
                info = self._compute_partition_info(data, part1, part2)

                if info < min_info:
                    min_info = info
                    best_partition = (part1, part2)

        return best_partition, min_info

    def _find_mip_greedy(
        self,
        data: np.ndarray
    ) -> Tuple[Tuple[Tuple[int, ...], Tuple[int, ...]], float]:
        """
        Find minimum information partition using greedy search.

        Starts with one element in each partition and greedily
        moves elements to minimize information.
        """
        n_dims = data.shape[1]

        if n_dims <= 2:
            return self._find_mip_exhaustive(data)

        # Start with random split
        indices = list(range(n_dims))
        np.random.shuffle(indices)
        part1 = set(indices[:n_dims // 2])
        part2 = set(indices[n_dims // 2:])

        # Greedy improvement
        improved = True
        max_iterations = 100
        iteration = 0

        while improved and iteration < max_iterations:
            improved = False
            iteration += 1

            best_move = None
            best_info = self._compute_partition_info(
                data, tuple(part1), tuple(part2)
            )

            # Try moving each element
            for elem in list(part1):
                if len(part1) > 1:
                    new_part1 = part1 - {elem}
                    new_part2 = part2 | {elem}
                    info = self._compute_partition_info(
                        data, tuple(new_part1), tuple(new_part2)
                    )
                    if info < best_info:
                        best_info = info
                        best_move = ('1to2', elem)

            for elem in list(part2):
                if len(part2) > 1:
                    new_part1 = part1 | {elem}
                    new_part2 = part2 - {elem}
                    info = self._compute_partition_info(
                        data, tuple(new_part1), tuple(new_part2)
                    )
                    if info < best_info:
                        best_info = info
                        best_move = ('2to1', elem)

            if best_move:
                improved = True
                direction, elem = best_move
                if direction == '1to2':
                    part1.remove(elem)
                    part2.add(elem)
                else:
                    part2.remove(elem)
                    part1.add(elem)

        return (tuple(sorted(part1)), tuple(sorted(part2))), best_info

    def _find_mip_random(
        self,
        data: np.ndarray,
        n_samples: int = 100
    ) -> Tuple[Tuple[Tuple[int, ...], Tuple[int, ...]], float]:
        """
        Find minimum information partition by random sampling.
        """
        n_dims = data.shape[1]
        indices = list(range(n_dims))

        min_info = float('inf')
        best_partition = (tuple(indices), ())

        for _ in range(n_samples):
            # Random partition
            np.random.shuffle(indices)
            split = np.random.randint(1, n_dims)
            part1 = tuple(sorted(indices[:split]))
            part2 = tuple(sorted(indices[split:]))

            info = self._compute_partition_info(data, part1, part2)

            if info < min_info:
                min_info = info
                best_partition = (part1, part2)

        return best_partition, min_info

    def _compute_partition_info(
        self,
        data: np.ndarray,
        part1: Tuple[int, ...],
        part2: Tuple[int, ...]
    ) -> float:
        """
        Compute information for a partition.

        Returns sum of effective information in each part.
        """
        if len(part1) == 0 or len(part2) == 0:
            return float('inf')

        data1 = data[:, list(part1)]
        data2 = data[:, list(part2)]

        info1 = self._compute_effective_information(data1)
        info2 = self._compute_effective_information(data2)

        return info1 + info2

    def find_minimum_information_partition(
        self,
        latent_codes: np.ndarray
    ) -> Dict:
        """
        Find the Minimum Information Partition (MIP).

        The MIP is the partition that minimizes integrated information,
        revealing the system's weakest point of integration.

        Parameters
        ----------
        latent_codes : ndarray
            Latent representations

        Returns
        -------
        dict
            MIP information including partition and integration strength
        """
        n_dims = latent_codes.shape[1]

        if n_dims <= self.max_partition_size:
            mip, min_info = self._find_mip_exhaustive(latent_codes)
        else:
            mip, min_info = self._find_mip_greedy(latent_codes)

        return {
            'mip': mip,
            'part1_size': len(mip[0]),
            'part2_size': len(mip[1]),
            'partition_info': float(min_info),
            'integration_strength': float(
                self._compute_effective_information(latent_codes) - min_info
            )
        }

    def analyze_cause_effect_structure(
        self,
        latent_codes: np.ndarray,
        time_lag: int = 1
    ) -> Dict:
        """
        Analyze the cause-effect structure of the system.

        Computes how each dimension causally influences others.

        Parameters
        ----------
        latent_codes : ndarray
            Latent representations (assumed to be time-ordered)
        time_lag : int, default=1
            Time lag for causal analysis

        Returns
        -------
        dict
            Cause-effect analysis results
        """
        n_samples, n_dims = latent_codes.shape

        if n_samples < time_lag + 10:
            return {
                'causal_matrix': np.zeros((n_dims, n_dims)),
                'total_causation': 0.0,
                'message': 'Not enough samples for causal analysis'
            }

        # Create lagged data
        past = latent_codes[:-time_lag]
        future = latent_codes[time_lag:]

        # Compute causal influence matrix
        causal_matrix = np.zeros((n_dims, n_dims))

        for i in range(n_dims):
            for j in range(n_dims):
                # Information from dimension i at t to dimension j at t+lag
                causal_matrix[i, j] = self._compute_transfer_entropy(
                    past[:, i], future[:, j]
                )

        # Summary statistics
        total_causation = np.sum(causal_matrix)
        self_causation = np.trace(causal_matrix)
        cross_causation = total_causation - self_causation

        # Find strongest causal links
        flat_idx = np.argsort(causal_matrix.flatten())[::-1]
        top_links = []
        for idx in flat_idx[:10]:
            i, j = divmod(idx, n_dims)
            if causal_matrix[i, j] > 0:
                top_links.append({
                    'from': int(i),
                    'to': int(j),
                    'strength': float(causal_matrix[i, j])
                })

        return {
            'causal_matrix': causal_matrix,
            'total_causation': float(total_causation),
            'self_causation': float(self_causation),
            'cross_causation': float(cross_causation),
            'top_causal_links': top_links
        }

    def _compute_transfer_entropy(
        self,
        source: np.ndarray,
        target: np.ndarray,
        n_bins: int = 10
    ) -> float:
        """
        Compute transfer entropy from source to target.

        TE(X->Y) = H(Y_t | Y_{t-1}) - H(Y_t | Y_{t-1}, X_{t-1})
        """
        if len(source) < 10 or len(target) < 10:
            return 0.0

        # Bin the data
        source_binned = np.digitize(source, np.linspace(source.min(), source.max(), n_bins))
        target_binned = np.digitize(target, np.linspace(target.min(), target.max(), n_bins))

        # Compute conditional entropies
        # H(Y_t | Y_{t-1})
        h_y_given_ypast = self._conditional_entropy_1d(target_binned, n_bins)

        # H(Y_t | Y_{t-1}, X_{t-1}) - approximated
        h_y_given_all = self._conditional_entropy_2d(target_binned, source_binned, n_bins)

        te = max(0.0, h_y_given_ypast - h_y_given_all)

        return te

    def _conditional_entropy_1d(self, data: np.ndarray, n_bins: int) -> float:
        """Compute H(X_t | X_{t-1})."""
        if len(data) < 2:
            return 0.0

        past = data[:-1]
        future = data[1:]

        # Joint histogram
        joint, _, _ = np.histogram2d(past, future, bins=n_bins)
        joint = joint + 1e-10
        joint = joint / joint.sum()

        # Marginal of past
        marginal = joint.sum(axis=1)
        marginal = marginal / marginal.sum()

        # H(X_t, X_{t-1}) - H(X_{t-1})
        h_joint = -np.sum(joint * np.log2(joint + 1e-10))
        h_marginal = -np.sum(marginal * np.log2(marginal + 1e-10))

        return h_joint - h_marginal

    def _conditional_entropy_2d(
        self,
        target: np.ndarray,
        source: np.ndarray,
        n_bins: int
    ) -> float:
        """Approximate H(Y_t | Y_{t-1}, X_{t-1})."""
        if len(target) < 2 or len(source) < 2:
            return 0.0

        # Combine past states
        combined = target[:-1] * n_bins + source[:-1]
        future = target[1:]

        # Joint histogram
        n_combined = n_bins * n_bins
        joint, _, _ = np.histogram2d(
            combined,
            future,
            bins=[n_combined, n_bins]
        )
        joint = joint + 1e-10
        joint = joint / joint.sum()

        # Marginal
        marginal = joint.sum(axis=1)
        marginal = marginal / marginal.sum()

        h_joint = -np.sum(joint * np.log2(joint + 1e-10))
        h_marginal = -np.sum(marginal * np.log2(marginal + 1e-10))

        return h_joint - h_marginal

    def compute_integrated_information_decomposition(
        self,
        latent_codes: np.ndarray
    ) -> Dict:
        """
        Decompose integrated information into components.

        Analyzes redundancy, synergy, and unique information
        in the system.

        Parameters
        ----------
        latent_codes : ndarray
            Latent representations

        Returns
        -------
        dict
            Information decomposition results
        """
        n_samples, n_dims = latent_codes.shape

        # Total information
        total_info = self._compute_effective_information(latent_codes)

        # Compute information for each dimension
        dim_info = []
        for i in range(n_dims):
            single_dim_info = self._compute_effective_information(
                latent_codes[:, i:i + 1]
            )
            dim_info.append(single_dim_info)

        sum_individual = sum(dim_info)

        # Synergy: information present in whole but not in parts
        synergy = max(0.0, total_info - sum_individual)

        # Redundancy: overlap between dimensions
        # Approximated as sum of pairwise mutual information
        redundancy = 0.0
        for i in range(n_dims):
            for j in range(i + 1, n_dims):
                mi = self._compute_mutual_information(
                    latent_codes[:, i],
                    latent_codes[:, j]
                )
                redundancy += mi

        return {
            'total_information': float(total_info),
            'sum_individual': float(sum_individual),
            'synergy': float(synergy),
            'redundancy': float(redundancy),
            'dimension_information': [float(d) for d in dim_info],
            'integration_ratio': float(synergy / (total_info + 1e-10))
        }

    def _compute_mutual_information(
        self,
        x: np.ndarray,
        y: np.ndarray,
        n_bins: int = 10
    ) -> float:
        """Compute mutual information between two arrays."""
        # Histograms
        px, _ = np.histogram(x, bins=n_bins, density=True)
        py, _ = np.histogram(y, bins=n_bins, density=True)
        pxy, _, _ = np.histogram2d(x, y, bins=n_bins, density=True)

        px = px + 1e-10
        py = py + 1e-10
        pxy = pxy + 1e-10

        px = px / px.sum()
        py = py / py.sum()
        pxy = pxy / pxy.sum()

        # H(X) + H(Y) - H(X,Y)
        hx = -np.sum(px * np.log2(px))
        hy = -np.sum(py * np.log2(py))
        hxy = -np.sum(pxy * np.log2(pxy))

        return max(0.0, hx + hy - hxy)

    def analyze(
        self,
        latent_codes: np.ndarray,
        verbose: bool = True
    ) -> Dict:
        """
        Run complete IIT analysis.

        Parameters
        ----------
        latent_codes : ndarray
            Latent representations
        verbose : bool, default=True
            Print results

        Returns
        -------
        dict
            Complete IIT analysis results
        """
        # Compute phi
        phi_result = self.compute_phi(latent_codes)

        # Find MIP
        mip_result = self.find_minimum_information_partition(latent_codes)

        # Cause-effect structure
        ce_result = self.analyze_cause_effect_structure(latent_codes)

        # Information decomposition
        decomp_result = self.compute_integrated_information_decomposition(
            latent_codes
        )

        if verbose:
            print("=" * 60)
            print("INTEGRATED INFORMATION THEORY ANALYSIS")
            print("=" * 60)
            print(f"System dimensions: {latent_codes.shape[1]}")
            print(f"Samples: {latent_codes.shape[0]}")
            print()

            print("Integrated Information (Phi):")
            print("-" * 40)
            print(f"  Phi (normalized): {phi_result['phi']:.4f}")
            print(f"  Phi (raw): {phi_result['phi_unnormalized']:.4f}")
            print(f"  Whole system info: {phi_result['whole_system_info']:.4f}")
            print(f"  Best partition info: {phi_result['partition_info']:.4f}")
            print()

            print("Minimum Information Partition:")
            print("-" * 40)
            print(f"  Part 1: {mip_result['mip'][0]} (size={mip_result['part1_size']})")
            print(f"  Part 2: {mip_result['mip'][1]} (size={mip_result['part2_size']})")
            print(f"  Integration strength: {mip_result['integration_strength']:.4f}")
            print()

            print("Cause-Effect Structure:")
            print("-" * 40)
            print(f"  Total causation: {ce_result['total_causation']:.4f}")
            print(f"  Self-causation: {ce_result['self_causation']:.4f}")
            print(f"  Cross-causation: {ce_result['cross_causation']:.4f}")
            if ce_result['top_causal_links']:
                print("  Top causal links:")
                for link in ce_result['top_causal_links'][:3]:
                    print(f"    {link['from']} -> {link['to']}: "
                          f"{link['strength']:.4f}")
            print()

            print("Information Decomposition:")
            print("-" * 40)
            print(f"  Total information: {decomp_result['total_information']:.4f}")
            print(f"  Synergy: {decomp_result['synergy']:.4f}")
            print(f"  Redundancy: {decomp_result['redundancy']:.4f}")
            print(f"  Integration ratio: {decomp_result['integration_ratio']:.4f}")
            print("=" * 60)

        return {
            'phi': phi_result,
            'mip': mip_result,
            'cause_effect': ce_result,
            'decomposition': decomp_result
        }


# Convenience function
def compute_consciousness_phi(latent_codes: np.ndarray, verbose: bool = False) -> float:
    """
    Quick computation of integrated information (Phi).

    Parameters
    ----------
    latent_codes : ndarray
        Latent codes from VAE
    verbose : bool, default=False
        Print details

    Returns
    -------
    float
        Normalized Phi value
    """
    analyzer = IITAnalyzer()
    result = analyzer.compute_phi(latent_codes)

    if verbose:
        print(f"Phi = {result['phi']:.4f}")

    return result['phi']
