"""
Export sync_report.md to PDF using ReportLab.
Produces: e:\AGI model\reports\sync_report.pdf
"""
from pathlib import Path
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Preformatted
from reportlab.lib.units import mm
import datetime

ROOT = Path(r"e:\AGI model")
REPORT = ROOT / "reports" / "sync_report.md"
OUT = ROOT / "reports" / "sync_report.pdf"

if not REPORT.exists():
    raise SystemExit(f"Report not found: {REPORT}")

text = REPORT.read_text(encoding='utf-8')

# Build PDF
doc = SimpleDocTemplate(str(OUT), pagesize=A4,
                        rightMargin=20*mm, leftMargin=20*mm,
                        topMargin=20*mm, bottomMargin=20*mm)
styles = getSampleStyleSheet()
styleN = styles['Normal']
styleH = styles['Heading1']
stylePre = ParagraphStyle('pre', fontName='Courier', fontSize=9, leading=12)

story = []

# Title
story.append(Paragraph('TMT-OS Sync Report', styleH))
story.append(Spacer(1, 6))
story.append(Paragraph(f'Generated: {datetime.datetime.utcnow().isoformat()} UTC', styleN))
story.append(Spacer(1, 12))

# Add content as preformatted to preserve tables
story.append(Preformatted(text, stylePre))

# Footer note
story.append(Spacer(1, 12))
story.append(Paragraph('Note: This report contains cryptographic provenance and DNA blueprints generated by the Metatron Nervous System. Do not expose private keys or secret material.', styleN))


doc.build(story)
print(f"PDF generated: {OUT}")
